WIP

diff --git a/home/.lain/bin/aps b/home/.lain/bin/aps
--- a/home/.lain/bin/aps
+++ b/home/.lain/bin/aps
@@ -52,7 +52,7 @@ for source in "$@"; do
         adb push "$source" "$target_dir"
         printf "\n"
     else
-        printf "${RED}Error: '%s' does not exist.${NC}\n" "$source" >&2
+        printf "${RED}Error:${NC} '%s' does not exist.\n" "$source" >&2
     fi
 done
 
diff --git a/home/.lain/bin/cpf b/home/.lain/bin/cpf
--- a/home/.lain/bin/cpf
+++ b/home/.lain/bin/cpf
@@ -25,7 +25,7 @@ uri_list=""
 
 for file in "$@"; do
     if [[ ! -f "$file" ]]; then
-        printf "${RED}Error: '%s' is not a regular file.${NC}\n" "$file" >&2
+        printf "${RED}Error:${NC} '%s' is not a regular file.\n" "$file" >&2
         exit 1
     fi
 
