WIP

diff --git a/home/.lain/bin/aps b/home/.lain/bin/aps
--- a/home/.lain/bin/aps
+++ b/home/.lain/bin/aps
@@ -21,19 +21,13 @@ GREEN='\033[0;32m'      # 绿色
 BLUE='\033[0;34m'       # 蓝色
 NC='\033[0m'            # 重置色
 
-if [[ "$#" -eq 0 ]]; then
-    printf "Error: Invalid argument.\n" >&2
-    printf "Usage: %s <paths...>\n" "$(basename "$0")" >&2
-    exit 1
-fi
-
 # 检查设备是否连接
 if [[ -z "$(adb devices | tail -n +2 | grep -v '^$')" ]]; then
     printf "Error: 未检测到任何 ADB 连接的设备\n" >&2
     exit 1
 fi
 
-push() {
+adb_push() {
     # 路径校验, 目标可以是文件, 也可以是目录, 只要存在即可
     for item in "$@"; do
         if [[ ! -e "$item" && ! -L "$item" ]]; then
@@ -42,7 +36,7 @@ push() {
         fi
     done
 
-    local target_dir="/sdcard/aps_inbox"
+    local target_dir="/sdcard/inbox"
 
     if ! adb shell "mkdir -p '$target_dir'"; then
         printf "${RED}Error:${NC} 在 ADB 设备上创建目录 '%s' 失败\n" "$target_dir" >&2
@@ -55,11 +49,28 @@ push() {
         adb push "$source" "$target_dir"
         printf "\n"
     done
-
-    printf "Done.\n"
-
-    notify-send "ADB push" "all files have been transferred."
-    "$WM_SCRIPTS/play_audio.sh" "complete.oga"
 }
 
-push
+adb_pull() {
+    local source_dir="/sdcard/outbox"
+
+    if ! adb shell "test -d '$source_dir'"; then
+        printf "${RED}Error:${NC} ADB 设备源目录 '%s' 不存在\n" "$source_dir" >&2
+        exit 1
+    fi
+
+    printf "Pulling...\n"
+
+    adb pull "$source_dir" .
+}
+
+if [[ "$#" -eq 0 ]]; then
+    adb_pull
+else
+    adb_push
+fi
+
+printf "Done.\n"
+
+notify-send "aps" "transmission completed."
+"$WM_SCRIPTS/play_audio.sh" "complete.oga"
