WIP

diff --git a/home/.lain/bin/aps b/home/.lain/bin/aps
--- a/home/.lain/bin/aps
+++ b/home/.lain/bin/aps
@@ -33,6 +33,15 @@ if [[ "$#" -eq 0 ]]; then
     exit 1
 fi
 
+# 路径校验
+for item in "$@"; do
+    if [[ ! -e "$item" && ! -L "$item" ]]; then
+        printf "${RED}Error:${NC} '%s' does not exist.\n" "$item" >&2
+        exit 1
+    fi
+done
+
+# 检查设备是否连接
 if [[ -z "$(adb devices | tail -n +2 | grep -v '^$')" ]]; then
     printf "Error: 未检测到任何 ADB 连接的设备\n" >&2
     exit 1
@@ -41,19 +50,15 @@ fi
 target_dir="/sdcard/temp_dir_of_aps"
 
 if ! adb shell "mkdir -p '$target_dir'"; then
-    printf "Error: 在 ADB 设备上创建目录 '%s' 失败\n" "$target_dir" >&2
+    printf "${RED}Error:${NC} 在 ADB 设备上创建目录 '%s' 失败\n" "$target_dir" >&2
     exit 1
 fi
 
 for source in "$@"; do
-    if [[ -e "$source" ]]; then
-        file_size=$(du -sh --apparent-size "$source" | awk '{print $1}')
-        printf "Pushing: ${GREEN}%s${NC}  Size: ${BLUE}%s${NC}\n" "$source" "$file_size"
-        adb push "$source" "$target_dir"
-        printf "\n"
-    else
-        printf "${RED}Error:${NC} '%s' does not exist.\n" "$source" >&2
-    fi
+    file_size=$(du -sh --apparent-size "$source" | awk '{print $1}')
+    printf "Pushing: ${GREEN}%s${NC}  Size: ${BLUE}%s${NC}\n" "$source" "$file_size"
+    adb push "$source" "$target_dir"
+    printf "\n"
 done
 
 printf "Done.\n"
