WIP

diff --git a/home/.lain/bin/iudisk b/home/.lain/bin/iudisk
--- a/home/.lain/bin/iudisk
+++ b/home/.lain/bin/iudisk
@@ -12,23 +12,25 @@ for cmd in "${dependencies[@]}"; do
 done
 
 # 定义颜色
+BLACK='\033[0;30m'      # 黑色
 RED='\033[0;31m'        # 红色
 GREEN='\033[0;32m'      # 绿色
+MAGENTA='\033[0;35m'    # 紫色
 NC='\033[0m'            # 重置色
 
-# 配置变量
+# 定义 U 盘设备以及分区
 usb_dev="/dev/sda"
 usb_part="/dev/sda1"
 
 # 检查设备是否存在
 check_dev_exists() {
     if [[ ! -b "$usb_dev" ]]; then
-        printf "USB device %s not found\n" "$usb_dev" >&2
+        printf "${RED}USB device %s not found${NC}\n" "$usb_dev" >&2
         exit 1
     fi
 
     if [[ ! -b "$usb_part" ]]; then
-        printf "USB partition %s not found on device %s\n" "$usb_part" "$usb_dev" >&2
+        printf "${RED}USB partition %s not found on device %s${NC}\n" "$usb_part" "$usb_dev" >&2
         exit 1
     fi
 }
@@ -56,9 +58,9 @@ confirm() {
 check_dev_status() {
     if findmnt -n "$usb_part" &> /dev/null; then
         mount_path=$(findmnt -n -o TARGET "$usb_part")
-        printf "USB drive (%s) has been mounted at: %s\n" "$usb_part" "$mount_path"
+        printf "${GREEN}USB drive (%s) has been mounted at: %s${NC}\n" "$usb_part" "$mount_path"
     else
-        printf "USB drive (%s) is currently not mounted\n" "$usb_part"
+        printf "${BLACK}USB drive (%s) is currently not mounted${NC}\n" "$usb_part"
     fi
 }
 
@@ -66,7 +68,7 @@ check_dev_status() {
 do_mount() {
     if findmnt -n "$usb_part" &> /dev/null; then
         mount_path=$(findmnt -n -o TARGET "$usb_part")
-        printf "USB drive (%s) has been mounted at: %s\n" "$usb_part" "$mount_path"
+        printf "${MAGENTA}The USB drive is already mounted${NC}\n"
         exit 0
     fi
 
@@ -82,16 +84,16 @@ do_unmount() {
 
     if findmnt -n "$usb_part" &> /dev/null; then
         udisksctl unmount -b "$usb_part"
-        printf "USB drive has been unmounted\n"
+        printf "${GREEN}USB drive has been unmounted${NC}\n"
     fi
 
     udisksctl power-off -b "$usb_dev"
-    printf "USB drive has been safely removed\n"
+    printf "${GREEN}USB drive has been safely removed${NC}\n"
 }
 
 # 检查参数是否等于 1
 if [[ "$#" -ne 1 ]]; then
-    printf "Error: Invalid arguments.\n" >&2
+    printf "${RED}Error: Invalid arguments.${NC}\n" >&2
     usage >&2
     exit 1
 fi
