WIP

diff --git a/home/bin/aps b/home/bin/aps
--- a/home/bin/aps
+++ b/home/bin/aps
@@ -11,13 +11,13 @@
 # -=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=-
 
 if ! command -v "adb" &> /dev/null; then
-    printf "Error: 缺少依赖命令: adb\n" >&2
+    printf "Error: Missing dependency: adb\n" >&2
     exit 1
 fi
 
 if [[ "$#" -eq 0 ]]; then
-    printf "参数错误\n" >&2
-    printf "用法: %s <file>...\n" "$(basename "$0")" >&2
+    printf "Error: Invalid argument.\n" >&2
+    printf "Usage: %s <file>...\n" "$(basename "$0")" >&2
     exit 1
 fi
 
diff --git a/home/bin/cpf b/home/bin/cpf
--- a/home/bin/cpf
+++ b/home/bin/cpf
@@ -10,7 +10,7 @@
 # -=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=-
 
 if ! command -v "wl-copy" &> /dev/null; then
-    printf "Error: 缺少依赖命令: wl-copy\n" >&2
+    printf "Error: Missing dependency: wl-copy\n" >&2
     exit 1
 fi
 
